// <auto-generated />
namespace SmartCoziness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedbookinginitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedbookinginitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201904141209092_added-booking-initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
